export enum AuthRepositoryEnum {
  AUDIT_REPOSITORY = 'AUDIT_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
}

export enum CoreRepositoryEnum {
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  LOCATION_REPOSITORY = 'LOCATION_REPOSITORY',
  CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY',
  PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY',
  SIGNATURE_REPOSITORY = 'SIGNATURE_REPOSITORY',
  INCOME_REPOSITORY = 'INCOME_REPOSITORY',
  EXPENSE_REPOSITORY = 'EXPENSE_REPOSITORY',
  TRANSACTION_IN_DETAIL_REPOSITORY = 'TRANSACTION_IN_DETAIL_REPOSITORY',  
  TRANSACTION_OUT_DETAIL_REPOSITORY = 'TRANSACTION_OUT_DETAIL_REPOSITORY',  
}



